language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/before_script.sh

script:
  - vendor/bin/phpcs --standard=phpcs.ruleset.xml
  - vendor/bin/phpunit --config=phpunit.xml.dist
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
