stages:
  - test
  - deploy

notifications:
  email:
    on_success: never
    on_failure: change

.composer_cache: &composer_cache
  cache:
    directories:
      - $HOME/.composer/
      - ./vendor/

.deploy_code_coverage: &deploy_code_coverage
  before_deploy:
    - cd dist/coverage
    - mv .css css
    - mv .fonts fonts
    - mv .js js
    - find ./ -type f -exec sed -i 's/\.css\//css\//g' {} \;
    - find ./ -type f -exec sed -i 's/\.fonts\//fonts\//g' {} \;
    - find ./ -type f -exec sed -i 's/\.js\//js\//g' {} \;
  deploy:
    provider: pages
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: dist/coverage
    on: "*"
    skip_cleanup: true

.php_unit: &php_unit_template
  before_script: bash bin/before_script.sh
  script: vendor/bin/phpunit --config=phpunit.xml.dist
  after_success: bash <(curl -s https://codecov.io/bash)
  language: php
  <<: *composer_cache

matrix:
  include:
    - name: 'PHP Code Sniffer'
      before_script: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --classmap-authoritative;
      script: vendor/bin/phpcs --standard=phpcs.ruleset.xml
      language: php
      <<: *composer_cache
    - php: 7.1
      env: WP_VERSION=4.0 WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.2
      env: WP_VERSION=4.0 WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.3
      env: WP_VERSION=4.0 WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.4
      env: WP_VERSION=4.0 WP_MULTISITE=0
      <<: *php_unit_template
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=0
      <<: *php_unit_template
      <<: *deploy_code_coverage
