language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --classmap-authoritative

script:
  - vendor/bin/phpcs --standard=phpcs.ruleset.xml
  - vendor/bin/phpunit --configuration=phpunit.xml.dist
